branches:
  only:
  - master
language: python
sudo: false
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- "./build-docs.sh"
after_success:
- git config --global user.email "evangelists@stormpath.com"
- git config --global user.name "stormpath-dotnet-documentation Auto Doc Build"
- git clone git@github.com:stormpath/stormpath.github.io.git
- cd stormpath.github.io
- git fetch origin source:source
- git checkout source
- rm -rf source/dotnet/aspnet/latest
- rm -rf source/dotnet/aspnetcore/latest
- cp -r ../docs/_build/html/aspnet source/dotnet/aspnet/latest
- cp -r ../docs/_build/html/aspnetcore source/dotnet/aspnetcore/latest
- git add --all
- git commit -m "stormpath-dotnet-documentation release latest"
- git push origin source
before_install:
- openssl aes-256-cbc -K $encrypted_2dc57c743138_key -iv $encrypted_2dc57c743138_iv
  -in keypair.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
